import "./globals.css";
import type { Metadata } from "next";
import Link from "next/Link";
import { Inter } from "next/font/google";
import Providers from "./providers";
import ThemeButton from "@/components/theme-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="py-4 px-24">
            <nav className="flex justify-between">
              <ul>
                <li>
                  <Link href="/">Home</Link>
                </li>
              </ul>
              <ThemeButton />
            </nav>
          </header>
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
